---
metallb_version: "v0.13.12"
metallb_namespace: "metallb-system"
metallb_ip_range: "192.168.100.210-192.168.100.250"
metallb_manifest_url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
metallb_wait_timeout: 300
