---
domain_name: "mz4.re"

k3s_version: "v1.33.6+k3s1"
k3s_token: "AAAAC3NzaC1lZDI1NTE5AAAAIB8Ts6oxASAAAAC3NzaC1lZDI1NTE5AAAAIB8Ts6oxASAAAAC3NzaC1lZDI1NTE5AAAAIB8Ts6oxAS"
k3s_primary_master: "node1"
k3s_primary_master_ip: "192.168.100.200"
k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"
k3s_config_dir: "/etc/rancher/k3s"
k3s_data_dir: "/var/lib/rancher/k3s"

metallb_version: "v0.15.3"
metallb_namespace: "metallb-system"
metallb_ip_range: "192.168.100.210-192.168.100.250"

longhorn_version: "v1.10.1"
longhorn_namespace: "longhorn-system"

traefik_version: "v3.6.4"
traefik_namespace: "traefik"


