cert_manager_namespace: "cert-manager"
cert_manager_version: "v1.14.4"
cert_manager_manifest_url: "https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml"
cert_manager_wait_timeout: 300