---
- name: Restart WireGuard
  service:
    name: "wg-quick@{{ wg_interface }}"
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: reloaded

- name: Save IPTables Rules
  become: yes
  shell: netfilter-persistent save